# Generated by Django 4.2.1 on 2023-06-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='visitor@audionote.com', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notesystem.user'),
        ),
    ]
